### ISSUE TITLE
Error sending emails using private SMTP server

### ISSUE THREAD

**Issue by suprexus** [microrealestate/microrealestate#212]
I'm able to send emails using mailgun, however, when I try using my own smtp server, I'm getting this in the console:

Rent.js:137 
 GET https://domain/api/v2/rents/2024/11 401 (Unauthorized)
fetch.js:131 POST /authenticator/landlord/refreshtoken 200
2
fetch.js:131 GET /rents/2024/11 200
index.mjs:307 Warning: Missing `Description` or `aria-describedby={undefined}` for {DialogContent}.
3
fetch.js:131 GET /rents/2024/11 200
Rent.js:137 
 GET https://domain/api/v2/rents/2024/11 401 (Unauthorized)
fetch.js:131 POST /authenticator/landlord/refreshtoken 200
2
fetch.js:131 GET /rents/2024/11 200
Rent.js:244 
 POST https://domain/api/v2/emails 504 (Gateway Timeout)
fetch.js:151 
X {message: 'Request failed with status code 504', name: 'AxiosError', code: 'ERR_BAD_RESPONSE', config: {…}, request: XMLHttpRequest, …}
Rent.js:137 
 GET https://domain/api/v2/rents/2024/11 401 (Unauthorized)
fetch.js:131 POST /authenticator/landlord/refreshtoken 200
2
fetch.js:131 GET /rents/2024/11 200

**Comment by suprexus** [comment]
I don't see the login attempt on the SMTP server side.

**Comment by camelaissani** [comment]
Do you have any docker logs in the terminal?

**Comment by suprexus** [comment]
Yes: 

### API Container:

2024-11-12T23:18:48.4848 <W> TokenExpiredError: jwt expired
2024-11-12T23:18:48.4848 <I> GET 401 2ms /api/v2/leases
2024-11-12T23:18:48.4848 <W> TokenExpiredError: jwt expired
2024-11-12T23:18:48.4848 <I> GET 401 1ms /api/v2/tenants
2024-11-12T23:18:48.4848 <W> TokenExpiredError: jwt expired
2024-11-12T23:18:48.4848 <I> GET 401 2ms /api/v2/properties
2024-11-12T23:18:48.4848 <W> TokenExpiredError: jwt expired
2024-11-12T23:18:48.4848 <I> GET 401 1ms /api/v2/dashboard
2024-11-12T23:18:48.4848 <W> accessToken not passed in the request
2024-11-12T23:18:48.4848 <I> GET 401 1ms /api/v2/leases
2024-11-12T23:18:48.4848 <W> accessToken not passed in the request
2024-11-12T23:18:48.4848 <I> GET 401 1ms /api/v2/tenants
2024-11-12T23:18:48.4848 <W> accessToken not passed in the request
2024-11-12T23:18:48.4848 <I> GET 401 1ms /api/v2/properties
2024-11-12T23:18:48.4848 <W> accessToken not passed in the request
2024-11-12T23:18:48.4848 <I> GET 401 1ms /api/v2/dashboard
2024-11-12T23:18:57.5757 <I> GET 304 4ms /api/v2/realms
2024-11-12T23:18:57.5757 <I> GET 304 27ms /api/v2/dashboard
2024-11-12T23:18:57.5757 <I> GET 304 33ms /api/v2/tenants
2024-11-12T23:18:57.5757 <I> GET 304 35ms /api/v2/properties
2024-11-12T23:18:57.5757 <I> GET 304 30ms /api/v2/leases
2024-11-12T23:19:09.099 <I> GET http://emailer:8400/emailer/status/2024110100/2024113023
2024-11-12T23:19:09.099 <I> GET http://emailer:8400/emailer/status/2024110100/2024113023 200
2024-11-12T23:19:09.099 <I> GET 304 19ms /api/v2/rents/2024/11
2024-11-12T23:19:35.3535 <W> TokenExpiredError: jwt expired
2024-11-12T23:19:35.3535 <I> GET 401 5ms /api/v2/rents/2024/11
2024-11-12T23:19:35.3535 <I> GET http://emailer:8400/emailer/status/2024110100/2024113023
2024-11-12T23:19:35.3535 <I> GET http://emailer:8400/emailer/status/2024110100/2024113023 200
2024-11-12T23:19:35.3535 <I> GET 304 38ms /api/v2/rents/2024/11
2024-11-12T23:19:45.4545 <I> POST http://emailer:8400/emailer
2024-11-12T23:19:49.4949 <I> GET http://emailer:8400/emailer/status/2024110100/2024113023
2024-11-12T23:19:49.4949 <I> GET http://emailer:8400/emailer/status/2024110100/2024113023 200
2024-11-12T23:19:49.4949 <I> GET 304 16ms /api/v2/rents/2024/11
2024-11-12T23:19:55.5555 <I> GET http://emailer:8400/emailer/status/2024110100/2024113023
2024-11-12T23:19:55.5555 <I> GET http://emailer:8400/emailer/status/2024110100/2024113023 200
2024-11-12T23:19:55.5555 <I> GET 304 42ms /api/v2/rents/2024/11
2024-11-12T23:20:41.4141 <W> TokenExpiredError: jwt expired
2024-11-12T23:20:41.4141 <I> GET 401 5ms /api/v2/rents/2024/11
2024-11-12T23:20:41.4141 <I> GET http://emailer:8400/emailer/status/2024110100/2024113023
2024-11-12T23:20:41.4141 <I> GET http://emailer:8400/emailer/status/2024110100/2024113023 200
2024-11-12T23:20:41.4141 <I> GET 304 20ms /api/v2/rents/2024/11
2024-11-12T23:21:45.4545 <E> Request failed with status code 500
2024-11-12T23:21:45.4545 <E> POST http://emailer:8400/emailer failed
2024-11-12T23:21:45.4545 <E> data sent: {"templateName":"invoice","recordId":"672fe1f04695cae36586c26c","params":{"term":2024110100}}
2024-11-12T23:21:45.4545 <E> Connection timeout
2024-11-12T23:21:45.4545 <E> undefined
2024-11-12T23:21:45.4545 <I> POST 500 120359ms /api/v2/emails

### Emailer

2024-11-12T23:19:09.099 <I> GET 200 7ms /emailer/status/2024110100/2024113023
2024-11-12T23:19:35.3535 <I> GET 200 12ms /emailer/status/2024110100/2024113023
2024-11-12T23:19:49.4949 <I> GET 200 6ms /emailer/status/2024110100/2024113023
2024-11-12T23:19:55.5555 <I> GET 200 14ms /emailer/status/2024110100/2024113023
2024-11-12T23:20:41.4141 <I> GET 200 6ms /emailer/status/2024110100/2024113023
2024-11-12T23:21:45.4545 <E> Error: Connection timeout
2024-11-12T23:21:45.4545 <I> POST 500 120322ms /emailer
2024-11-12T23:23:29.2929 <I> GET 200 22ms /emailer/status/2024110100/2024113023


### Landlord Frontend

AxiosError: Request failed with status code 403
    at settle (file:///usr/app/node_modules/axios/lib/core/settle.js:19:12)
    at IncomingMessage.handleStreamEnd (file:///usr/app/node_modules/axios/lib/adapters/http.js:599:11)
    at IncomingMessage.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (file:///usr/app/node_modules/axios/lib/core/Axios.js:45:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_BAD_REQUEST',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http', 'fetch' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/x-www-form-urlencoded',
      'User-Agent': 'axios/1.7.7',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    baseURL: 'http://gateway:8080/api/v2',
    withCredentials: true,
    method: 'post',
    url: '/authenticator/landlord/refreshtoken',
    data: undefined
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      finish: [Function: requestOnFinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: false,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    strictContentLength: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: false,
    socket: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'gateway',
      _closeAfterHandlingError: false,
      _events: [Object],
      _readableState: [ReadableState],
      _writableState: [WritableState],
      allowHalfOpen: false,
      _maxListeners: undefined,
      _eventsCount: 7,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      timeout: 5000,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(async_id_symbol)]: 5859,
      [Symbol(kHandle)]: [TCP],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: Timeout {
        _idleTimeout: 5000,
        _idlePrev: [TimersList],
        _idleNext: [TimersList],
        _idleStart: 7649939,
        _onTimeout: [Function: bound ],
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: false,
        [Symbol(refed)]: false,
        [Symbol(kHasPrimitive)]: false,
        [Symbol(asyncId)]: 5858,
        [Symbol(triggerId)]: 0
      },
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(shapeMode)]: true,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: true,
      [Symbol(kSetKeepAlive)]: true,
      [Symbol(kSetKeepAliveInitialDelay)]: 60,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    _header: 'POST /api/v2/authenticator/landlord/refreshtoken HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Content-Type: application/x-www-form-urlencoded\r\n' +
      'User-Agent: axios/1.7.7\r\n' +
      'Accept-Encoding: gzip, compress, deflate, br\r\n' +
      'Host: gateway:8080\r\n' +
      'Connection: keep-alive\r\n' +
      'Content-Length: 0\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 80,
      protocol: 'http:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype],
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: true,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'POST',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    joinDuplicateHeaders: undefined,
    path: '/api/v2/authenticator/landlord/refreshtoken',
    _ended: true,
    res: IncomingMessage {
      _events: [Object],
      _readableState: [ReadableState],
      _maxListeners: undefined,
      socket: [Socket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      joinDuplicateHeaders: undefined,
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 403,
      statusMessage: 'Forbidden',
      client: [Socket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      _eventsCount: 4,
      responseUrl: 'http://gateway:8080/api/v2/authenticator/landlord/refreshtoken',
      redirects: [],
      [Symbol(shapeMode)]: true,
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 14,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0
    },
    aborted: false,
    timeoutCb: [Function: emitRequestTimeout],
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'gateway',
    protocol: 'http:',
    _redirectable: Writable {
      _events: [Object],
      _writableState: [WritableState],
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _eventsCount: 3,
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'http://gateway:8080/api/v2/authenticator/landlord/refreshtoken',
      [Symbol(shapeMode)]: true,
      [Symbol(kCapture)]: false
    },
    [Symbol(shapeMode)]: false,
    [Symbol(kCapture)]: false,
    [Symbol(kBytesWritten)]: 0,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      'user-agent': [Array],
      'accept-encoding': [Array],
      host: [Array]
    },
    [Symbol(errored)]: null,
    [Symbol(kHighWaterMark)]: 16384,
    [Symbol(kRejectNonStandardBodyWrites)]: false,
    [Symbol(kUniqueHeaders)]: null
  },
  response: {
    status: 403,
    statusText: 'Forbidden',
    headers: Object [AxiosHeaders] {
      'x-powered-by': 'Express',
      vary: 'X-HTTP-Method-Override',
      'content-type': 'application/json; charset=utf-8',
      'content-length': '46',
      etag: 'W/"2e-rY/4F48e0DcWUq1oqDVDhzVsrEA"',
      date: 'Tue, 12 Nov 2024 23:18:48 GMT',
      connection: 'close'
    },
    config: {
      transitional: [Object],
      adapter: [Array],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      env: [Object],
      validateStatus: [Function: validateStatus],
      headers: [Object [AxiosHeaders]],
      baseURL: 'http://gateway:8080/api/v2',
      withCredentials: true,
      method: 'post',
      url: '/authenticator/landlord/refreshtoken',
      data: undefined
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: false,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'POST /api/v2/authenticator/landlord/refreshtoken HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/x-www-form-urlencoded\r\n' +
        'User-Agent: axios/1.7.7\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: gateway:8080\r\n' +
        'Connection: keep-alive\r\n' +
        'Content-Length: 0\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/api/v2/authenticator/landlord/refreshtoken',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: [Function: emitRequestTimeout],
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'gateway',
      protocol: 'http:',
      _redirectable: [Writable],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    data: { status: 403, message: 'invalid credentials' }
  },
  status: 403
}

**Comment by camelaissani** [comment]
Only the emailer service logs can help here.
This `2024-11-12T23:21:45.4545 Error: Connection timeout` seems to be the problem.
I need some time to configure a smtp server to test this again. Meanwhile could you ensure that your smtp server is reachable by the emailer service?

**Comment by suprexus** [comment]
Yeah it's reachable from all the MRE containers. My smtp server is public.

**Comment by sugoides** [comment]
I also have this issue

`2025-01-31T22:52:04.044 <E> Error: Connection timeout`
I''m using outlook smtp server

**Comment by sugoides** [comment]
@camelaissani any update on this?

> Only the emailer service logs can help here. This `2024-11-12T23:21:45.4545 Error: Connection timeout` seems to be the problem. I need some time to configure a smtp server to test this again. Meanwhile could you ensure that your smtp server is reachable by the emailer service?
